# Generated by Django 2.2.16 on 2022-05-22 09:05

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220522_0854'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Вы уже подписаны на этого автора.',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='Нельзя подписываться на себя.',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='Вы уже подписаны на этого автора.'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('following')), name='Нельзя подписываться на себя.'),
        ),
    ]
